SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 820

BETWEEN_PLAYER_LIST_CHAR = "="
END_PLAYER_LIST_CHAR = ";"

SCREEN_TITLE = "Space Invaders"

PLAYER_SIZE = 70
HEIGHT_OFFSET = 100

# Menu Constants
TEXT_FONT = "freesansbold.ttf"
TITLE_TXT_SIZE = 100
TITLE_TXT_CLR = (255, 255, 255)

STATUS_BAR_CONNECT_CLR = "#00FF00"
STATUS_BAR_CONNECT_TXT = "Connected"
STATUS_BAR_DISCONNECT_CLR = "#FF0000"
STATUS_BAR_DISCONNECT_TXT = "Disconnected"

GAME_NAME = "Space Invaders"
LOBBY_TITLE = "Lobby"