SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 820

BETWEEN_PLAYER_LIST_CHAR = "="
END_PLAYER_LIST_CHAR = ";"

SCREEN_TITLE = "Space Invaders"

PLAYER_SIZE = 70
HEIGHT_OFFSET = 100

# Menu Constants
TEXT_FONT = "freesansbold.ttf"
TITLE_TXT_SIZE = 100
TITLE_TXT_CLR = (255, 255, 255)

STARTGAME_BTN_TXT = "Start Game"
STARTGAME_BTN_FONT_SIZE = 32
STARTGAME_BTN_TXT_CLR = (0, 0, 0)
STARTGAME_BTN_COLOR = (255, 255, 255)
STARTGAME_BTN_COLOR_HOVER = (200, 200, 200)
STARTGAME_BTN_WIDTH = 400
STARTGAME_BTN_HEIGHT = 100
STARTGAME_BTN_TOP = 400
STARTGAME_BTN_LEFT = (SCREEN_WIDTH-STARTGAME_BTN_WIDTH)/2

GAME_NAME = "Space Invaders"
LOBBY_TITLE = "Lobby"