SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 820


BETWEEN_PLAYER_LIST_CHAR = "="
END_PLAYER_LIST_CHAR = ";"

SCREEN_TITLE = "Space Invaders"

PLAYER_SIZE = 70
HEIGHT_OFFSET = 100

# Menu Constants
TEXT_FONT = "freesansbold.ttf"
TITLE_TXT_SIZE = 100
TITLE_TXT_CLR = (255, 255, 255)

PURPLE_COLOR = (106, 13, 173)

GAME_NAME = "Space Invaders"
LOBBY_TITLE = "Lobby"