SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 820

BETWEEN_PLAYER_LIST_CHAR = "="
END_PLAYER_LIST_CHAR = ";"

SCREEN_TITLE = "Space Invaders"

PLAYER_SIZE = 70
HEIGHT_OFFSET = 100

# Menu Constants
TEXT_FONT = "freesansbold.ttf"
TITLE_TXT_SIZE = 100
TITLE_TXT_CLR = (255, 255, 255)

# Lobby Active Players List Constants
ACTPLALST_RECT_X = SCREEN_WIDTH/4
ACTPLALST_RECT_Y = SCREEN_HEIGHT/4
ACTPLALST_RECT_WIDTH = SCREEN_WIDTH/2
ACTPLALST_RECT_HEIGHT = SCREEN_HEIGHT/2
ACTPLALST_RECT_COLOR = (0, 0, 255)

ACTPLABTN_X = (ACTPLALST_RECT_X)+10
ACTPLABTN_WIDTH = (ACTPLALST_RECT_X)-20
ACTPLABTN_HEIGHT = ACTPLALST_RECT_HEIGHT / 10
ACTPLABTN_FONT_SIZE = ACTPLABTN_HEIGHT / 2
ACTPLABTN_COLOR = (255, 0, 0)
ACTPLABTN_COLOR_HOVER = (0, 200, 2)
ACTPLABTN_TXT_CLR = (0, 0, 0)

# Start Game Button Constants
STARTGAME_BTN_TXT = "Start Game"
STARTGAME_BTN_FONT_SIZE = 32
STARTGAME_BTN_TXT_CLR = (0, 0, 0)
STARTGAME_BTN_COLOR = (255, 255, 255)
STARTGAME_BTN_COLOR_HOVER = (0, 200, 2)
STARTGAME_BTN_WIDTH = 400
STARTGAME_BTN_HEIGHT = 100
STARTGAME_BTN_Y = 400
STARTGAME_BTN_X = (SCREEN_WIDTH-STARTGAME_BTN_WIDTH)/2

PURPLE_COLOR = (106, 13, 173)

GAME_NAME = "Space Invaders"
LOBBY_TITLE = "Lobby"