
SIGNINTITLETXT = "Sign In"
SIGNINTITLETXTHEIGHT = 1
SIGNINTXTFONT = ("Calibri", 100)
TITLEBGCLR = "#8E8E8E"

SCREENBGCOLOR = "#272727"

CONNECTIONSTATUSBARHEIGHT = 2

SIGNINBUTTONWIDTH = 10
SIGNINBUTTONHEIGHT = 1
BUTTONSPADDING_Y = 10
BTNFONT = ("Calibri", 50)
BTNBGCLR = "#CFCFCF"
BTNCLR_ON_CLICK = '#ABABAB'
