<MainGrid>


    GridLayout:
        size: root.width, root.height
        cols:1

        GridLayout:
            cols:2
            Label:
                text: "Name"
            TextInput:
                id: name
                multiline: False

        Button:
            text: "Submit"
    # GridLayout:

    #     size: root.width, root.height

    #     Label:
    #         text: "Hello"

    #     TextInput:
    #         multiline: False
            